apiVersion: v1
kind: ConfigMap
metadata:
  name: awbd-configmap
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8070/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8071/eureka/
  SPRING_DATASOURCE_URL: jdbc:mysql://10.8.3.245:3306/project_2?createDatabaseIfNotExist=true