apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: lauracozma/eureka:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
          - containerPort: 8071
          env:
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: awbd-configmap
                key: SPRING_CONFIG_IMPORT
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: awbd-configmap
                key: SPRING_PROFILES_ACTIVE
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: awbd-configmap
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071