apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
  labels:
    app: patient-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient
          image: lauracozma/patient-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: awbd-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: awbd-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: awbd-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

---

apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082