INSERT INTO MEDICATION VALUES (null, 'Ibuprofen', 300);
INSERT INTO MEDICATION VALUES (null, 'Ibuprofen', 800);
INSERT INTO MEDICATION VALUES (null, 'Paracetamol', 400);
INSERT INTO MEDICATION VALUES (null, 'Decasept', 50);
INSERT INTO MEDICATION VALUES (null, 'Colebil', 2);